### ISSUE TITLE
Force SMS over iMessage

### ISSUE THREAD

**Issue by BrendanThompson** [linjunpop/imessage#6]
Would it be possible to set a flag to force `imessage` to send the message as an SMS over an iMessage?

**Comment by troylo** [comment]
Hi Brendan, if you use this solutions that is not of all possible, because the system of iMessage detect if destinatary has an iCloud account and send by iMessage. to Check if is compatible with iMessage you can check result after send in the file chat.db (SQLITE) in the path ~/library/messages and read all status of the transaction and put a script that do anythings if is iMessage client or other things if isn´t iMessage client. B.Regards !

**Comment by andilabs** [comment]
is there any chance to start a new converstaion?

**Comment by KarinaFernandez** [comment]
Hi all! I´m starting to use your gem @linjunpop and is the unique that I can make it works! Thank you so much! 
Now I´m trying to get the result of the message after sending it but I don´t know where to starts. 
Have you success getting this @BrendanThompson or @troylo ? Could you please help me?

Thank you so much!

**Comment by CircleOnCircles** [comment]
Is there any way to check if the contact has icloud account?

or we just need to check the `~/library/messages/chat.db` after send
